version: '3.7'

services:
  app:
    image: registry.gitlab.com/minidigger/hangar
    depends_on:
      - 'db'
      - 'auth'
      - 'mail'
    stdin_open: true
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://hangar_db/ore"
      JDBC_DATABASE_PASSWORD: "changeme"
      SPONGE_AUTH_URL: "https://hangar-auth.minidigger.me"
      APPLICATION_SECRET: "some_secret"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar.loadbalancer.server.port=9000"
      - "traefik.http.routers.hangar.rule=Host(`hangar.minidigger.me`)"
      - "traefik.http.routers.hangar.entrypoints=web-secure"
      - "traefik.http.routers.hangar.tls=true"
      - "traefik.http.routers.hangar.tls.options=default"
      - "traefik.http.routers.hangar.tls.certresolver=default"
      - "traefik.http.routers.hangar.tls.domains[0].main=minidigger.me"
      - "traefik.http.routers.hangar.tls.domains[0].sans=*.minidigger.me"
    networks:
      - web
    volumes:
      - uploads:/home/ore/prod/uploads
  db:
    image: registry.gitlab.com/minidiggerdockerfiles/hangar-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'changeme'
      POSTGRES_DB: ore
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    networks:
      - web
  mail:
    image: mailhog/mailhog:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-mail.loadbalancer.server.port=8025"
      - "traefik.http.routers.hangar-mail.middlewares=basicauth@file"
      - "traefik.http.routers.hangar-mail.rule=Host(`hangar-mail.minidigger.me`)"
      - "traefik.http.routers.hangar-mail.entrypoints=web-secure"
      - "traefik.http.routers.hangar-mail.tls=true"
      - "traefik.http.routers.hangar-mail.tls.options=default"
      - "traefik.http.routers.hangar-mail.tls.certresolver=default"
      - "traefik.http.routers.hangar-mail.tls.domains[0].main=minidigger.me"
      - "traefik.http.routers.hangar-mail.tls.domains[0].sans=*.minidigger.me"
    networks:
      - web
  auth:
    image: registry.gitlab.com/minidigger/hangarauth
    depends_on:
      - 'db'
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-auth.loadbalancer.server.port=8000"
      - "traefik.http.routers.hangar-auth.rule=Host(`hangar-auth.minidigger.me`)"
      - "traefik.http.routers.hangar-auth.entrypoints=web-secure"
      - "traefik.http.routers.hangar-auth.tls=true"
      - "traefik.http.routers.hangar-auth.tls.options=default"
      - "traefik.http.routers.hangar-auth.tls.certresolver=default"
      - "traefik.http.routers.hangar-auth.tls.domains[0].main=minidigger.me"
      - "traefik.http.routers.hangar-auth.tls.domains[0].sans=*.minidigger.me"
    environment:
      SECRET_KEY: TzNc3RTpfVn1xxNV90PPGEfs7SZhy5
      EMAIL_HOST_USER: dum
      EMAIL_HOST_PASSWORD: dum
      DEBUG: false
      DJANGO_SETTINGS_MODULE: spongeauth.settings.prod
    networks:
      - web

networks:
  web:
    name: traefik-overlay
    external: true

volumes:
  db_data:
  uploads:
